name: CICD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} 
      - name: Build Docker image
        run: docker build -t abdilah007/testcicd-app .
      - name: Publish image to Docker Hub
        run: docker push abdilah007/testcicd-app:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from Docker Hub
        run: sudo docker pull abdilah007/testcicd-app:latest
      - name: Stop and remove old container 
        run: sudo docker rm -f testoneCICD-container || true
      - name: Run Docker container
        run: sudo docker run -d -p 5000:5000 --name testoneCICD-container abdilah007/testcicd-app
